version: '3.8'

services:
  shopping-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COOP_USERNAME=${COOP_USERNAME}
      - COOP_PASSWORD=${COOP_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_STORE=${DEFAULT_STORE:-coop_se}
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - shopping-network
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: shopping-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shopping-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  shopping-network:
    driver: bridge


