version: '3.8'

services:
  shopping-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COOP_USERNAME=${COOP_USERNAME}
      - COOP_PASSWORD=${COOP_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_STORE=${DEFAULT_STORE:-coop_se}
      - TEMPORAL_ADDRESS=temporal:7233
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - shopping-network
    depends_on:
      - redis
      - temporal
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: shopping-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shopping-network
    restart: unless-stopped

  temporal:
    image: temporalio/auto-setup:1.25.0
    container_name: temporal
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgres
      - POSTGRES_DB=temporal
      - TEMPORAL_NAMESPACE=default
    ports:
      - "7233:7233"
    networks:
      - shopping-network
    depends_on:
      - temporal-postgres
    restart: unless-stopped

  temporal-ui:
    image: temporalio/ui:2.31.2
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8080:8080"
    networks:
      - shopping-network
    depends_on:
      - temporal
    restart: unless-stopped

  temporal-postgres:
    image: postgres:15-alpine
    container_name: temporal-postgres
    environment:
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_USER=temporal
      - POSTGRES_DB=temporal
    networks:
      - shopping-network
    volumes:
      - temporal_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  temporal-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temporal-worker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COOP_USERNAME=${COOP_USERNAME}
      - COOP_PASSWORD=${COOP_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_STORE=${DEFAULT_STORE:-coop_se}
      - TEMPORAL_ADDRESS=temporal:7233
    command: ["bash", "-lc", "chmod +x src/workflows/worker_entry.sh && ./src/workflows/worker_entry.sh"]
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "6080:6080"  # noVNC viewer
    networks:
      - shopping-network
    depends_on:
      - temporal
    restart: unless-stopped

volumes:
  redis_data:
  temporal_pgdata:

networks:
  shopping-network:
    driver: bridge


